HOST: http://localhost:9000/

--- Seapal Play ---
--

make sure that you're logged in.
UUIDOfAccount looks like '523b7def-af42-4b3a-8eca-63a583f69ecf'
--

--
Boats
--
Get all boats that belong to the current user
GET /api/boat
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
[{
  "owner": "UUIDOfAccount",
  "crew": [],
  "boatName": "test4",
  "registerNr": "",
  "sailSign": "",
  "homePort": "",
  "yachtclub": "",
  "insurance": "",
  "callSign": "",
  "type": "",
  "constructor": "",
  "length": 0.0,
  "width": 0.0,
  "draft": 0.0,
  "mastHeight": 0.0,
  "displacement": 0.0,
  "rigging": "",
  "yearOfConstruction": 0,
  "motor": "",
  "tankSize": 0.0,
  "wasteWaterTankSize": 0.0,
  "freshWaterTankSize": 0.0,
  "mainSailSize": 0.0,
  "genuaSize": 0.0,
  "spiSize": 0.0,
  "_id": "010a0c10-4e6a-437e-87b6-cdcf7056d76f",
  "_rev": "2-6f53f9467726b2fa04ad1aedb0249562"
}]

--
This will add a new boat to the DB
POST /api/boat
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
[{
  "owner": "UUIDOfAccount",
  "crew": [],
  "boatName": "test4",
  "registerNr": "",
  "sailSign": "",
  "homePort": "",
  "yachtclub": "",
  "insurance": "",
  "callSign": "",
  "type": "",
  "constructor": "",
  "length": 0.0,
  "width": 0.0,
  "draft": 0.0,
  "mastHeight": 0.0,
  "displacement": 0.0,
  "rigging": "",
  "yearOfConstruction": 0,
  "motor": "",
  "tankSize": 0.0,
  "wasteWaterTankSize": 0.0,
  "freshWaterTankSize": 0.0,
  "mainSailSize": 0.0,
  "genuaSize": 0.0,
  "spiSize": 0.0,
  "_id": "010a0c10-4e6a-437e-87b6-cdcf7056d76f",
  "_rev": "2-6f53f9467726b2fa04ad1aedb0249562"
}]
< 201
{
    "success": true
}