HOST: http://localhost:9000/

--- Seapal Play ---
--

make sure that you're logged in.

UUIDOfAccount looks like '523b7def-af42-4b3a-8eca-63a583f69ecf'

![Image](http://yuml.me/0f1369e4)
--

-- General --
If you request a document you don't have access to, you'll receive an empty JSON array. If you're not logged in (Play Session cookie does not exist), you'll receive the following JSON object:
GET /restricted/url
< 401
< Content-Type: application/json
{
    "error": "unauthorized"
}

-- Boats --
Get all boats that belong to the currently logged in user.
GET /api/boat
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
[{
  "owner": "UUIDOfAccount",
  "crew": [],
  "boatName": "test4",
  "registerNr": "",
  "sailSign": "",
  "homePort": "",
  "yachtclub": "",
  "insurance": "",
  "callSign": "",
  "type": "",
  "constructor": "",
  "length": 0.0,
  "width": 0.0,
  "draft": 0.0,
  "mastHeight": 0.0,
  "displacement": 0.0,
  "rigging": "",
  "yearOfConstruction": 0,
  "motor": "",
  "tankSize": 0.0,
  "wasteWaterTankSize": 0.0,
  "freshWaterTankSize": 0.0,
  "mainSailSize": 0.0,
  "genuaSize": 0.0,
  "spiSize": 0.0,
  "_id": "010a0c10-4e6a-437e-87b6-cdcf7056d76f",
  "_rev": "2-6f53f9467726b2fa04ad1aedb0249562"
}]

Get a single boat. this is also an array. If the array is empty, the boat either doesn't exist or you don't have access to it.
GET /api/boat/$id<[0-9a-fA-F\-]+>
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
[{
  "owner": "523b7def-af42-4b3a-8eca-63a583f69ecf",
  "crew": [],
  "boatName": "test4",
  "registerNr": "",
  "sailSign": "",
  "homePort": "",
  "yachtclub": "",
  "insurance": "",
  "callSign": "",
  "type": "",
  "constructor": "",
  "length": 0.0,
  "width": 0.0,
  "draft": 0.0,
  "mastHeight": 0.0,
  "displacement": 0.0,
  "rigging": "",
  "yearOfConstruction": 0,
  "motor": "",
  "tankSize": 0.0,
  "wasteWaterTankSize": 0.0,
  "freshWaterTankSize": 0.0,
  "mainSailSize": 0.0,
  "genuaSize": 0.0,
  "spiSize": 0.0,
  "_id": "010a0c10-4e6a-437e-87b6-cdcf7056d76f",
  "_rev": "2-6f53f9467726b2fa04ad1aedb0249562"
}]

Add a new boat to the database. The field owner will be set to the id of the currently logged in user.
POST /api/boat
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
[{
  "owner": "UUIDOfAccount",
  "crew": [],
  "boatName": "test4",
  "registerNr": "",
  "sailSign": "",
  "homePort": "",
  "yachtclub": "",
  "insurance": "",
  "callSign": "",
  "type": "",
  "constructor": "",
  "length": 0.0,
  "width": 0.0,
  "draft": 0.0,
  "mastHeight": 0.0,
  "displacement": 0.0,
  "rigging": "",
  "yearOfConstruction": 0,
  "motor": "",
  "tankSize": 0.0,
  "wasteWaterTankSize": 0.0,
  "freshWaterTankSize": 0.0,
  "mainSailSize": 0.0,
  "genuaSize": 0.0,
  "spiSize": 0.0,
  "_id": "010a0c10-4e6a-437e-87b6-cdcf7056d76f",
  "_rev": "2-6f53f9467726b2fa04ad1aedb0249562"
}]
< 201
{
    "success": true
}

Delete a boat from the database.
DELETE /api/boat/$id<[0-9a-fA-F\-]+>
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
{
    "success": true
}

-- Trips --
Get all trips that belong to this boat.
GET /api/boat/$id<[0-9a-fA-F\-]+>/trips
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}

Get all trips that belong to the currently logged in user.
GET /api/trip
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}

Get a single trip.
GET /api/trip/$id<[0-9a-fA-F\-]+>
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}

Delete a trip.
DELETE /api/trip/$id<[0-9a-fA-F\-]+>
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}

Create a new trip.
POST /api/trip
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}

-- Waypoints --
Get all waypoints of a single trip.
GET /api/trip/$id<[0-9a-fA-F\-]+>/waypoints
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}

Get a single waypoint.
GET /api/waypoint/$waypointId<[0-9a-fA-F\-]+>
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}

Get all waypoints that belong to the currently logged in user.
POST /api/waypoint
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}

-- Routes --
Get all routes that belong to the currently logged in user.
GET /api/route
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}

Get a single route.
GET /api/route/$id<[0-9a-fA-F\-]+>
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}

Add a new route to the database. The field owner will be set to the id of the currently logged in user.
POST /api/route
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
{
    "error": "this isn't the JSON document you're looking for"
}
< 201
{
    "success": true
}

Delete a route from the database.
DELETE /api/route/$id<[0-9a-fA-F\-]+>
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
{
    "success": true
}

-- Marks --
Get all marks that belong to this boat.
GET /api/boat/$id<[0-9a-fA-F\-]+>/marks
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}

Get a single mark.
GET /api/mark/$id<[0-9a-fA-F\-]+>
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}

Delete a mark.
DELETE /api/mark/$id<[0-9a-fA-F\-]+>
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}

Create a new mark.
POST /api/mark
> Cookie: PLAY_SESSION="playInternalHash-id=UUIDOfAccount"
< 200
< Content-Type: application/json
{
    "error": "this isn't the JSON document you're looking for"
}
